---
development:
  cloud_name: brwnppl-inc
  api_key: '758483744588151'
  api_secret: 0fZLF07asEoHCLwWDLFtVLwDuIs
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: brwnppl-inc
  api_key: '758483744588151'
  api_secret: 0fZLF07asEoHCLwWDLFtVLwDuIs
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: brwnppl-inc
  api_key: '758483744588151'
  api_secret: 0fZLF07asEoHCLwWDLFtVLwDuIs
  enhance_image_tag: true
  static_image_support: false